FROM aprismaos-toolchain:base

# Install runtime tools
RUN apt update && apt install -y --no-install-recommends \
    make \
    git \
    libgmp10 \
    libmpfr6 \
    libmpc3 \
    grub-pc-bin \
    xorriso \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
CMD ["bash"]

